# 1. Classification_ML(SVM, LR, RF, DT, KNN)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:/AI_study/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [4]:
X = df.drop('Outcome', axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=32)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((576, 8), (192, 8), (576,), (192,))

In [6]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
clf_svm = SVC(random_state=32)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n------SVM Classifier-----------")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))

------SVM Classifier-----------
0.796875
[[113  10]
 [ 29  40]]

In [7]:
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=32)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
0.7708333333333334
[[104  19]
 [ 25  44]]

I:\anaconda3\envs\test01\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [8]:
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=32)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.7239583333333334
[[99 24]
 [29 40]]

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
clf_rf = RandomForestClassifier(random_state=32)
clf_rf.fit(X_train, y_train)
pred_rf = clf_rf.predict(X_test)
print(accuracy_score(y_test,pred_rf))
print (confusion_matrix(y_test, pred_rf))

--- Random Forest ---
0.765625
[[102  21]
 [ 24  45]]

# 2. Classification_DL

In [10]:
df = pd.read_csv("C:/AI_study/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [11]:
y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
df['Outcome'].value_counts

<bound method IndexOpsMixin.value_counts of 0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64>

In [13]:
X = df.drop('Outcome', axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=32)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((576, 8), (192, 8), (576,), (192,))

In [15]:
'''
from tensorflow.keras.utils import to_categorical

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

print(y_train_onehot.shape)
print(y_test_onehot.shape)
'''

'\nfrom tensorflow.keras.utils import to_categorical\n\ny_train_onehot = to_categorical(y_train)\ny_test_onehot = to_categorical(y_test)\n\nprint(y_train_onehot.shape)\nprint(y_test_onehot.shape)\n'

In [16]:
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Dense(100, activation='relu', input_shape=(8,)))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               900

 dense_1 (Dense)             (None, 1)                 101

=================================================================
Total params: 1,001
Trainable params: 1,001
Non-trainable params: 0
_________________________________________________________________

In [17]:
# validation_split = 0.1
batch_size = 128

train_epochs = 50
history = model.fit(X_train, y_train, epochs=train_epochs, batch_size=batch_size, verbose=True, shuffle=True)

Epoch 1/50
5/5 [==============================] - 1s 5ms/step - loss: 13.7470 - accuracy: 0.3420
Epoch 2/50
5/5 [==============================] - 0s 3ms/step - loss: 5.1949 - accuracy: 0.3559
Epoch 3/50
5/5 [==============================] - 0s 3ms/step - loss: 3.2640 - accuracy: 0.6076
Epoch 4/50
5/5 [==============================] - 0s 3ms/step - loss: 4.1783 - accuracy: 0.6389
Epoch 5/50
5/5 [==============================] - 0s 3ms/step - loss: 3.1370 - accuracy: 0.6250
Epoch 6/50
5/5 [==============================] - 0s 2ms/step - loss: 2.0149 - accuracy: 0.4635
Epoch 7/50
5/5 [==============================] - 0s 2ms/step - loss: 2.1390 - accuracy: 0.3733
Epoch 8/50
5/5 [==============================] - 0s 4ms/step - loss: 1.5293 - accuracy: 0.4844
Epoch 9/50
5/5 [==============================] - 0s 3ms/step - loss: 1.3965 - accuracy: 0.5972
Epoch 10/50
5/5 [==============================] - 0s 2ms/step - loss: 1.0758 - accuracy: 0.5382
Epoch 11/50
5/5 [==============================] - 0s 2ms/step - loss: 0.9266 - accuracy: 0.5486
Epoch 12/50
5/5 [==============================] - 0s 3ms/step - loss: 0.8233 - accuracy: 0.6146
Epoch 13/50
5/5 [==============================] - 0s 4ms/step - loss: 0.7430 - accuracy: 0.6042
Epoch 14/50
5/5 [==============================] - 0s 3ms/step - loss: 0.7153 - accuracy: 0.6042
Epoch 15/50
5/5 [==============================] - 0s 2ms/step - loss: 0.7003 - accuracy: 0.6510
Epoch 16/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6704 - accuracy: 0.6597
Epoch 17/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6606 - accuracy: 0.6788
Epoch 18/50
5/5 [==============================] - 0s 4ms/step - loss: 0.6531 - accuracy: 0.6736
Epoch 19/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6503 - accuracy: 0.6788
Epoch 20/50
5/5 [==============================] - 0s 4ms/step - loss: 0.6206 - accuracy: 0.6840
Epoch 21/50
5/5 [==============================] - 0s 3ms/step - loss: 0.6249 - accuracy: 0.6788
Epoch 22/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6126 - accuracy: 0.6892
Epoch 23/50
5/5 [==============================] - 0s 4ms/step - loss: 0.6116 - accuracy: 0.6892
Epoch 24/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6037 - accuracy: 0.6944
Epoch 25/50
5/5 [==============================] - 0s 4ms/step - loss: 0.6013 - accuracy: 0.6910
Epoch 26/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5976 - accuracy: 0.7101
Epoch 27/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5984 - accuracy: 0.6944
Epoch 28/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6139 - accuracy: 0.7014
Epoch 29/50
5/5 [==============================] - 0s 3ms/step - loss: 0.6051 - accuracy: 0.6962
Epoch 30/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5920 - accuracy: 0.7066
Epoch 31/50
5/5 [==============================] - 0s 2ms/step - loss: 0.6030 - accuracy: 0.6979
Epoch 32/50
5/5 [==============================] - 0s 8ms/step - loss: 0.6126 - accuracy: 0.7031
Epoch 33/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5966 - accuracy: 0.7049
Epoch 34/50
5/5 [==============================] - 0s 4ms/step - loss: 0.6019 - accuracy: 0.7170
Epoch 35/50
5/5 [==============================] - 0s 2ms/step - loss: 0.5877 - accuracy: 0.6979
Epoch 36/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5764 - accuracy: 0.6979
Epoch 37/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5755 - accuracy: 0.7170
Epoch 38/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5715 - accuracy: 0.7153
Epoch 39/50
5/5 [==============================] - 0s 2ms/step - loss: 0.5792 - accuracy: 0.7083
Epoch 40/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5727 - accuracy: 0.7170
Epoch 41/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5648 - accuracy: 0.7135
Epoch 42/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5702 - accuracy: 0.7153
Epoch 43/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5694 - accuracy: 0.7014
Epoch 44/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5690 - accuracy: 0.7101
Epoch 45/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5632 - accuracy: 0.7170
Epoch 46/50
5/5 [==============================] - 0s 2ms/step - loss: 0.5631 - accuracy: 0.7083
Epoch 47/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5591 - accuracy: 0.7153
Epoch 48/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5631 - accuracy: 0.7135
Epoch 49/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5714 - accuracy: 0.7083
Epoch 50/50
5/5 [==============================] - 0s 2ms/step - loss: 0.5842 - accuracy: 0.6858

In [18]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix

y_pred = model.predict(X_test)

6/6 [==============================] - 0s 1ms/step

In [19]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix

y_pred = (y_pred > 0.5).astype(int)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.85      0.77       123
           1       0.58      0.36      0.45        69

    accuracy                           0.68       192
   macro avg       0.64      0.61      0.61       192
weighted avg       0.66      0.68      0.66       192

[[105  18]
 [ 44  25]]

# 3. Regression_ML

In [20]:
df = pd.read_csv("C:/AI_study/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [21]:
X = df.drop('Outcome',axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [22]:
y = X['BMI']
y

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ...
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64

In [23]:
X= X.drop('BMI',axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,0.627,50
1,1,85,66,29,0,0.351,31
2,8,183,64,0,0,0.672,32
3,1,89,66,23,94,0.167,21
4,0,137,40,35,168,2.288,33
...,...,...,...,...,...,...,...
763,10,101,76,48,180,0.171,63
764,2,122,70,27,0,0.340,27
765,5,121,72,23,112,0.245,30
766,1,126,60,0,0,0.349,47
767,1,93,70,31,0,0.315,23

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=32)

In [26]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeRegressor

clf_dt = DecisionTreeRegressor()
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print(clf_dt.score(X_train, y_train))

1.0

In [33]:
mse = np.sqrt(mean_squared_error(pred_dt, y_test))
print('mse', mse)

mse 8.238210781663508

In [40]:
from sklearn.ensemble import RandomForestRegressor

rf_clf = RandomForestRegressor()
rf_clf.fit(X_train, y_train)

pred_rf = rf_clf.predict(X_test)

print(rf_clf.score(X_train, y_train))

0.8904744101301253

In [41]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('mse', mse)

mse 6.076137158280233

In [42]:
from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print(clf_lr.score(X_train, y_train))

0.20424338953905097

In [43]:
mse = np.sqrt(mean_squared_error(pred_lr, y_test))
print('mse', mse)

mse 7.07155582695871

In [44]:
from sklearn.svm import SVR

clf_svm = SVR()
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print(clf_svm.score(X_train, y_train))

0.16673600308443848

In [45]:
mse = np.sqrt(mean_squared_error(pred_svm, y_test))
print('mse', mse)

mse 7.39826487930863

# 4. Regression_DL

In [46]:
df = pd.read_csv("C:/AI_study/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [47]:
X = df.drop('Outcome',axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [48]:
y = X['BMI']
y

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ...
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64

In [49]:
X= X.drop('BMI',axis=1)
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,0.627,50
1,1,85,66,29,0,0.351,31
2,8,183,64,0,0,0.672,32
3,1,89,66,23,94,0.167,21
4,0,137,40,35,168,2.288,33
...,...,...,...,...,...,...,...
763,10,101,76,48,180,0.171,63
764,2,122,70,27,0,0.340,27
765,5,121,72,23,112,0.245,30
766,1,126,60,0,0,0.349,47
767,1,93,70,31,0,0.315,23

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=32)

In [54]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Dense(100, activation='relu', input_shape=(7,)))  # 입력은 8개의 feature
model.add(Dense(1))  # 출력 뉴런 1개, 회귀 문제이므로 활성화 함수 없음 (linear)

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 100)               800

 dense_5 (Dense)             (None, 1)                 101

=================================================================
Total params: 901
Trainable params: 901
Non-trainable params: 0
_________________________________________________________________

In [55]:
# validation_split = 0.1
batch_size = 128

train_epochs = 50
history = model.fit(X_train, y_train, epochs=train_epochs, batch_size=batch_size, verbose=True, shuffle=True)

Epoch 1/50
5/5 [==============================] - 0s 7ms/step - loss: 1120.3765 - mse: 1120.3765
Epoch 2/50
5/5 [==============================] - 0s 7ms/step - loss: 481.4824 - mse: 481.4824
Epoch 3/50
5/5 [==============================] - 0s 6ms/step - loss: 315.8969 - mse: 315.8969
Epoch 4/50
5/5 [==============================] - 0s 6ms/step - loss: 239.6796 - mse: 239.6796
Epoch 5/50
5/5 [==============================] - 0s 3ms/step - loss: 145.1602 - mse: 145.1602
Epoch 6/50
5/5 [==============================] - 0s 3ms/step - loss: 94.2784 - mse: 94.2784
Epoch 7/50
5/5 [==============================] - 0s 2ms/step - loss: 92.3594 - mse: 92.3594
Epoch 8/50
5/5 [==============================] - 0s 4ms/step - loss: 91.9068 - mse: 91.9068
Epoch 9/50
5/5 [==============================] - 0s 3ms/step - loss: 84.6771 - mse: 84.6771
Epoch 10/50
5/5 [==============================] - 0s 4ms/step - loss: 79.8434 - mse: 79.8434
Epoch 11/50
5/5 [==============================] - 0s 7ms/step - loss: 74.8789 - mse: 74.8789
Epoch 12/50
5/5 [==============================] - 0s 3ms/step - loss: 69.4715 - mse: 69.4715
Epoch 13/50
5/5 [==============================] - 0s 13ms/step - loss: 67.6376 - mse: 67.6376
Epoch 14/50
5/5 [==============================] - 0s 2ms/step - loss: 65.9379 - mse: 65.9379
Epoch 15/50
5/5 [==============================] - 0s 4ms/step - loss: 63.2455 - mse: 63.2455
Epoch 16/50
5/5 [==============================] - 0s 2ms/step - loss: 61.5556 - mse: 61.5556
Epoch 17/50
5/5 [==============================] - 0s 3ms/step - loss: 59.6320 - mse: 59.6320
Epoch 18/50
5/5 [==============================] - 0s 3ms/step - loss: 58.4934 - mse: 58.4934
Epoch 19/50
5/5 [==============================] - 0s 2ms/step - loss: 56.9469 - mse: 56.9469
Epoch 20/50
5/5 [==============================] - 0s 3ms/step - loss: 56.2114 - mse: 56.2114
Epoch 21/50
5/5 [==============================] - 0s 3ms/step - loss: 55.1325 - mse: 55.1325
Epoch 22/50
5/5 [==============================] - 0s 4ms/step - loss: 54.3670 - mse: 54.3670
Epoch 23/50
5/5 [==============================] - 0s 2ms/step - loss: 53.5962 - mse: 53.5962
Epoch 24/50
5/5 [==============================] - 0s 4ms/step - loss: 53.2280 - mse: 53.2280
Epoch 25/50
5/5 [==============================] - 0s 2ms/step - loss: 52.3012 - mse: 52.3012
Epoch 26/50
5/5 [==============================] - 0s 3ms/step - loss: 52.3118 - mse: 52.3118
Epoch 27/50
5/5 [==============================] - 0s 2ms/step - loss: 51.5698 - mse: 51.5698
Epoch 28/50
5/5 [==============================] - 0s 3ms/step - loss: 51.0955 - mse: 51.0955
Epoch 29/50
5/5 [==============================] - 0s 2ms/step - loss: 50.5040 - mse: 50.5040
Epoch 30/50
5/5 [==============================] - 0s 5ms/step - loss: 50.0927 - mse: 50.0927
Epoch 31/50
5/5 [==============================] - 0s 2ms/step - loss: 49.7030 - mse: 49.7030
Epoch 32/50
5/5 [==============================] - 0s 5ms/step - loss: 49.4601 - mse: 49.4601
Epoch 33/50
5/5 [==============================] - 0s 2ms/step - loss: 49.2981 - mse: 49.2981
Epoch 34/50
5/5 [==============================] - 0s 5ms/step - loss: 48.7814 - mse: 48.7814
Epoch 35/50
5/5 [==============================] - 0s 2ms/step - loss: 48.6286 - mse: 48.6286
Epoch 36/50
5/5 [==============================] - 0s 2ms/step - loss: 48.1894 - mse: 48.1894
Epoch 37/50
5/5 [==============================] - 0s 3ms/step - loss: 48.0104 - mse: 48.0104
Epoch 38/50
5/5 [==============================] - 0s 2ms/step - loss: 47.7818 - mse: 47.7818
Epoch 39/50
5/5 [==============================] - 0s 2ms/step - loss: 47.5222 - mse: 47.5222
Epoch 40/50
5/5 [==============================] - 0s 2ms/step - loss: 47.3140 - mse: 47.3140
Epoch 41/50
5/5 [==============================] - 0s 2ms/step - loss: 47.1707 - mse: 47.1707
Epoch 42/50
5/5 [==============================] - 0s 2ms/step - loss: 46.9996 - mse: 46.9996
Epoch 43/50
5/5 [==============================] - 0s 3ms/step - loss: 46.7461 - mse: 46.7461
Epoch 44/50
5/5 [==============================] - 0s 2ms/step - loss: 46.6181 - mse: 46.6181
Epoch 45/50
5/5 [==============================] - 0s 2ms/step - loss: 46.3518 - mse: 46.3518
Epoch 46/50
5/5 [==============================] - 0s 4ms/step - loss: 46.1756 - mse: 46.1756
Epoch 47/50
5/5 [==============================] - 0s 2ms/step - loss: 46.1792 - mse: 46.1792
Epoch 48/50
5/5 [==============================] - 0s 2ms/step - loss: 45.8202 - mse: 45.8202
Epoch 49/50
5/5 [==============================] - 0s 2ms/step - loss: 45.6975 - mse: 45.6975
Epoch 50/50
5/5 [==============================] - 0s 3ms/step - loss: 45.4588 - mse: 45.4588

In [56]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix

y_pred = model.predict(X_test)

6/6 [==============================] - 0s 997us/step

In [58]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# y_pred는 회귀 모델의 예측값
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R² (R-squared): {r2}")

Mean Squared Error (MSE): 50.05520228780737
Mean Absolute Error (MAE): 5.212384450435638
R² (R-squared): 0.287313761041177